

spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  datasource:
    username: sample
    password: sample1!
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/temp?serverTimezone=UTC&allowPublicKeyRetrieval=true


