server.port: 8081

spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  datasource:
    username: sample
    password: sample1!
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/temp?serverTimezone=UTC&allowPublicKeyRetrieval=true
  batch:
    initialize-schema.enabled: false
    job.enabled: false
#  main:
#    allow-bean-definition-overriding: true

url:
  back: http://localhost:8080
